set(NLOHMANN_JSON_TARGET_NAME           nlohmann_json)
set(NLOHMANN_JSON_VERSION 3.1.2)
set(NLOHMANN_JSON_PROJECT_SOURCE_DIR    ${EXTERNAL_PROJECTS_PREFIX}/v${NLOHMANN_JSON_VERSION})
set(NLOHMANN_JSON_INCLUDE_BUILD_DIR     ${NLOHMANN_JSON_PROJECT_SOURCE_DIR})
set(INCLUDE_URL https://github.com/nlohmann/json/releases/download/v${NLOHMANN_JSON_VERSION}/include.zip)

set(INSTALL_COMMAND ${CMAKE_COMMAND} -E copy_directory ${NLOHMANN_JSON_PROJECT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR}/src)

# configure_file(
#     ${CMAKE_CURRENT_SOURCE_DIR}/cmake/uninstall.cmake.in
#     ${CMAKE_CURRENT_BINARY_DIR}/cmake/uninstall.cmake
#     IMMEDIATE @ONLY
# )

ExternalProject_Add(nlohmann-json
    PREFIX              ${EXTERNAL_PROJECTS_PREFIX}
    SOURCE_DIR          ${NLOHMANN_JSON_PROJECT_SOURCE_DIR}
    URL                 ${INCLUDE_URL}
    UPDATE_DISCONNECTED 1
    DOWNLOAD_DIR        ${NLOHMANN_JSON_PROJECT_SOURCE_DIR}
    CONFIGURE_COMMAND   "${CMAKE_COMMAND}" -E remove_directory "${CMAKE_CURRENT_SOURCE_DIR}/src"
    BUILD_COMMAND       "${CMAKE_COMMAND}" -E make_directory "${CMAKE_CURRENT_SOURCE_DIR}/src"
    INSTALL_COMMAND     ${INSTALL_COMMAND}
    DOWNLOAD_NO_EXTRACT ${EXTRACT_OPTION}
)
